name: Release Python OpenCV App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # specify your desired Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy opencv-python

    - name: Build binary
      run: pyinstaller --onefile your_app.py  # replace `your_app.py` with the main file of your application

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Binary release of the Python OpenCV app.
        draft: false
        prerelease: false
